id: I674F9433
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:20:00+00:00'
last_modified: '2022-06-07T12:06:32.354821+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21743
  title: གནའ་གཏམ་མཐོང་བ་དགའ་སྐྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    1C18:
      image_group_id: I1KG12584
      title: Volume 1 of mdo mang /
      total_pages: 756
      order: 1
      base_file: 1C18.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
